[build]
  command = "npm install"
  functions = "functions"  # Update this if you have serverless functions
  publish = "public"

[[headers]]
  for = "/public/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200
